# Generated by Django 3.0.5 on 2020-06-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positterapp', '0007_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='positive_score',
            field=models.IntegerField(null=True),
        ),
    ]
